# see: http://docs.travis-ci.com/user/languages/perl/
# see: http://blogs.perl.org/users/neilb/2014/08/try-travis-ci-with-your-cpan-distributions.html
language: perl
perl:
  - "5.18"
  - "5.16"
#  - "5.14"
#  - "5.12"
#  - "5.10"
install:
  - cpanm --quiet --notest Devel::Cover
  - cpanm -n -q --skip-satisfied --notest --installdeps .
# docs for options: http://search.cpan.org/~pjcj/Devel-Cover-1.17/lib/Devel/Cover.pm
script:
  - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine,-ignore,prove,t/ prove -lr t
  - cover
after_success:
  - cover -report coveralls